services:
  jupyter:
    image: quay.io/jupyter/pyspark-notebook:2025-11-29
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
      - ./docker/spark-defaults.conf:/usr/local/spark/conf/spark-defaults.conf
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
