services:
  jupyter:
    image: quay.io/jupyter/pyspark-notebook:2025-11-29
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
