spark.jars.packages                   io.delta:delta-spark_4.0_2.13:4.2.0
spark.sql.extensions                  io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog       org.apache.spark.sql.delta.catalog.DeltaCatalog